### PR TITLE
Fix env.get issue

### PR DESCRIPTION
**Pull request by natcl**
Not sure how it even worked before... added it to the sandbox

### CODE REVIEW

**Comment by natcl** [comment]
Please pull this in as it fixes the issue with env not working in 0.20 thanks !

**Comment by natcl** [comment]
Polite bump :)

**Comment by natcl** [comment]
Thanks!! :)

**Comment by ozomer** [comment]
Published on npm - version 0.8.0.
I haven't touched node-red for years, didn't even test your changes. I hope you didn't introduce any bug. If you want to take over this repository, please let me know.

**Comment by natcl** [comment]
I’d be glad if you add me as contributor, we use that node heavily at work so will make sure to maintain it.


--
lecaude.com 
studioimaginaire.com

**Comment by ozomer** [comment]
I think I added you to the github project correctly.
What is your npm username?

**Comment by natcl** [comment]
natcl

Thanks a lot !


--
lecaude.com 
studioimaginaire.com

**Comment by ozomer** [comment]
You're welcome :)

P.S. You should enable 2 factor authentication on npm! It's 2019, npm should enforce it on everyone...

**Comment by natcl** [comment]
Indeed will do right away thanks !


--
lecaude.com 
studioimaginaire.com

**Pull request merged**
